/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.mailingsystem.view;

import edu.ijse.mailingsystem.connector.ServerConnector;
import edu.ijse.mailingsystem.controller.UserController;
import edu.ijse.mailingsystem.dto.UserDTO;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dulan
 */
public class SignUpPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignUpPanel
     */
    public SignUpPanel() {
        initComponents();
        showPasswordLable.setVisible(false);
        confirmPasswordOK.setVisible(false);
        confirmPasswordNotOK.setVisible(false);
        textUserId.setEditable(false);
        textUserId.setText("UI0000");
    }

    SignUpPanel(UserDTO user) {
//        initComponents();
//        showPasswordLable.setVisible(false);
//        confirmPasswordOK.setVisible(false);
//        confirmPasswordNotOK.setVisible(false);
//        textUserId.setText(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textUserId = new javax.swing.JTextField();
        textUserName = new javax.swing.JTextField();
        textFirstName = new javax.swing.JTextField();
        textLastName = new javax.swing.JTextField();
        passwordUserPassword = new javax.swing.JPasswordField();
        showPasswordLable = new javax.swing.JLabel();
        showPassword = new javax.swing.JLabel();
        lableUserNameAvailability = new javax.swing.JLabel();
        signUpButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        passwordUserPasswordConfirm = new javax.swing.JPasswordField();
        confirmPasswordOK = new javax.swing.JLabel();
        confirmPasswordNotOK = new javax.swing.JLabel();

        setOpaque(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sign Up", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Bright", 3, 19), new java.awt.Color(0, 51, 153))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 165, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("URW Bookman L", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("User Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 98, 168, 32));

        jLabel2.setFont(new java.awt.Font("URW Bookman L", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("User ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 47, 168, 32));

        jLabel3.setFont(new java.awt.Font("URW Bookman L", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("First Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 158, 168, 32));

        jLabel4.setFont(new java.awt.Font("URW Bookman L", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 208, 168, 32));

        jLabel5.setFont(new java.awt.Font("URW Bookman L", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 1, 1));
        jLabel5.setText("User Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 258, 168, 32));
        jPanel1.add(textUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 46, 315, 32));

        textUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUserNameActionPerformed(evt);
            }
        });
        jPanel1.add(textUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 97, 315, 32));
        jPanel1.add(textFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 157, 315, 32));
        jPanel1.add(textLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 208, 315, 32));
        jPanel1.add(passwordUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 258, 254, 32));
        jPanel1.add(showPasswordLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 250, 30));

        showPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showPassword.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\Second Sem Project\\MailingSystemClient\\src\\edu\\ijse\\mailingsystem\\image\\show_hide_password-05-128 (1).png")); // NOI18N
        showPassword.setBorder(new javax.swing.border.MatteBorder(null));
        showPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showPasswordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                showPasswordMouseReleased(evt);
            }
        });
        jPanel1.add(showPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 258, 49, 30));
        jPanel1.add(lableUserNameAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 134, 315, 17));

        signUpButton.setFont(new java.awt.Font("Miriam Fixed", 1, 18)); // NOI18N
        signUpButton.setForeground(new java.awt.Color(0, 165, 255));
        signUpButton.setText("Sign Up");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        jPanel1.add(signUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 140, -1));

        jLabel7.setFont(new java.awt.Font("URW Bookman L", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 1, 1));
        jLabel7.setText("Confirm Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 310, 168, 27));

        passwordUserPasswordConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordUserPasswordConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(passwordUserPasswordConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 308, 254, -1));

        confirmPasswordOK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmPasswordOK.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\Second Sem Project\\MailingSystemClient\\src\\edu\\ijse\\mailingsystem\\image\\correct-symbol-clipart-best-hg 30.png")); // NOI18N
        confirmPasswordOK.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(confirmPasswordOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 308, 49, 29));

        confirmPasswordNotOK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmPasswordNotOK.setIcon(new javax.swing.ImageIcon("D:\\IJSE\\Project\\Second Sem Project\\MailingSystemClient\\src\\edu\\ijse\\mailingsystem\\image\\6a011570391c4a970c01a3fd06b553.png")); // NOI18N
        confirmPasswordNotOK.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(confirmPasswordNotOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 308, 49, 29));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        try {
            String userId = textUserId.getText();
            String userName = textUserName.getText().toLowerCase();
            String firstName = textFirstName.getText().toLowerCase();
            String lastName = textLastName.getText().toLowerCase();
            String password = passwordUserPassword.getText();
            String confirmPassword = passwordUserPasswordConfirm.getText();
            String userType = "User";
//            if (checkboxAdmin.isSelected()) {
//                userType = "admin";
//            } else {
//                userType = "user";
//            }

            if (password.equals(confirmPassword)) {
                UserDTO user = new UserDTO(userId, userName, firstName, lastName, password, userType);
                UserController userController = ServerConnector.getServerConnector().getUserController();
                boolean availability = userController.userNameAvailability(userName);
                if (availability) {
//                    lableUserNameAvailability.setText("UserDTO Name is Available");
                    boolean isUser = userController.addUser(user);
                    if (isUser) {
                        HomePage homePage = new HomePage(userName);
                        this.setVisible(false);
                        homePage.setVisible(true);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "User Name is already Used");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Password Harida Balapan...");
            }

        } catch (NotBoundException ex) {
            Logger.getLogger(UserMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(UserMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(UserMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(UserMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void textUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUserNameActionPerformed
        try {
            UserController userController = ServerConnector.getServerConnector().getUserController();
            boolean availability = userController.userNameAvailability(textUserName.getText().toLowerCase());
            textUserName.setText(textUserName.getText().toLowerCase());
            textFirstName.setEditable(availability);
            textLastName.setEditable(availability);
            passwordUserPassword.setEditable(availability);
            passwordUserPasswordConfirm.setEditable(availability);

            if (availability) {
                lableUserNameAvailability.setText("User Name eka ela bn...");
            } else {
                lableUserNameAvailability.setText("Ade user Name eka use karala bn.. ");
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(SignUpPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(SignUpPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(SignUpPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SignUpPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_textUserNameActionPerformed

    private void showPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPasswordMousePressed
        String password = passwordUserPassword.getText();
        showPasswordLable.setText(password);
        showPasswordLable.setVisible(true);
        passwordUserPassword.setVisible(false);
    }//GEN-LAST:event_showPasswordMousePressed

    private void showPasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPasswordMouseReleased
        showPasswordLable.setText("");
        showPasswordLable.setVisible(false);
        passwordUserPassword.setVisible(true);
    }//GEN-LAST:event_showPasswordMouseReleased

    private void passwordUserPasswordConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordUserPasswordConfirmActionPerformed
        if (passwordUserPassword.getText().equals(passwordUserPasswordConfirm.getText())) {
            confirmPasswordOK.setVisible(true);
            confirmPasswordNotOK.setVisible(false);
        } else {
            confirmPasswordNotOK.setVisible(true);
            confirmPasswordOK.setVisible(false);
        }
    }//GEN-LAST:event_passwordUserPasswordConfirmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confirmPasswordNotOK;
    private javax.swing.JLabel confirmPasswordOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lableUserNameAvailability;
    private javax.swing.JPasswordField passwordUserPassword;
    private javax.swing.JPasswordField passwordUserPasswordConfirm;
    private javax.swing.JLabel showPassword;
    private javax.swing.JLabel showPasswordLable;
    private javax.swing.JButton signUpButton;
    private javax.swing.JTextField textFirstName;
    private javax.swing.JTextField textLastName;
    private javax.swing.JTextField textUserId;
    private javax.swing.JTextField textUserName;
    // End of variables declaration//GEN-END:variables
}
